// Module wrapper function is the function that is automatically generated by node:
// (function (exports, require, module, __filename, __dirname) {

raja = {
  name: "Aditya",
  favNum: 3,
  developer: true,
};

// Printing the elements of Module Wrapper Function:
// console.log(exports, require, module, __filename, __dirname);

module.exports = raja;
// });
